// <auto-generated />
using GameVault.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameVault.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251129165836_SeedAdditionalGames")]
    partial class SeedAdditionalGames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameVault.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Description = "An open-world action-adventure game set in the kingdom of Hyrule.",
                            Genre = "Action-Adventure",
                            Platform = "Nintendo Switch",
                            ReleaseYear = 2017,
                            Title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 101,
                            Description = "An epic tale of life in America's unforgiving heartland.",
                            Genre = "Action-Adventure",
                            Platform = "PlayStation 5",
                            ReleaseYear = 2018,
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 102,
                            Description = "A rogue-like dungeon crawler where you defy the god of the dead.",
                            Genre = "Roguelike",
                            Platform = "PC",
                            ReleaseYear = 2020,
                            Title = "Hades"
                        },
                        new
                        {
                            Id = 103,
                            Description = "A fantasy action RPG developed by FromSoftware and George R.R. Martin.",
                            Genre = "Action RPG",
                            Platform = "PC",
                            ReleaseYear = 2022,
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 104,
                            Description = "A challenging platformer about climbing a mountain and overcoming personal struggles.",
                            Genre = "Platformer",
                            Platform = "Nintendo Switch",
                            ReleaseYear = 2018,
                            Title = "Celeste"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
